//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowToggler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListInvisibleWindow {
            get {
                return ((bool)(this["ListInvisibleWindow"]));
            }
            set {
                this["ListInvisibleWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListUntitledWindow {
            get {
                return ((bool)(this["ListUntitledWindow"]));
            }
            set {
                this["ListUntitledWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseHotKey {
            get {
                return ((bool)(this["UseHotKey"]));
            }
            set {
                this["UseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseMiddleButtonDown {
            get {
                return ((bool)(this["UseMiddleButtonDown"]));
            }
            set {
                this["UseMiddleButtonDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSimultaneousLeftRightDown {
            get {
                return ((bool)(this["UseSimultaneousLeftRightDown"]));
            }
            set {
                this["UseSimultaneousLeftRightDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseMouseMoveOut {
            get {
                return ((bool)(this["UseMouseMoveOut"]));
            }
            set {
                this["UseMouseMoveOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseHideThisAppHotKey {
            get {
                return ((bool)(this["UseHideThisAppHotKey"]));
            }
            set {
                this["UseHideThisAppHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TargetAppList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TargetAppList"]));
            }
            set {
                this["TargetAppList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string ModifierKey1ComboBox {
            get {
                return ((string)(this["ModifierKey1ComboBox"]));
            }
            set {
                this["ModifierKey1ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string ModifierKey2ComboBox {
            get {
                return ((string)(this["ModifierKey2ComboBox"]));
            }
            set {
                this["ModifierKey2ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string ModifierKey3ComboBox {
            get {
                return ((string)(this["ModifierKey3ComboBox"]));
            }
            set {
                this["ModifierKey3ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string VirtualKeyComboBox {
            get {
                return ((string)(this["VirtualKeyComboBox"]));
            }
            set {
                this["VirtualKeyComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string ThisModifierKey1ComboBox {
            get {
                return ((string)(this["ThisModifierKey1ComboBox"]));
            }
            set {
                this["ThisModifierKey1ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string ThisModifierKey2ComboBox {
            get {
                return ((string)(this["ThisModifierKey2ComboBox"]));
            }
            set {
                this["ThisModifierKey2ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string ThisModifierKey3ComboBox {
            get {
                return ((string)(this["ThisModifierKey3ComboBox"]));
            }
            set {
                this["ThisModifierKey3ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string ThisVirtualKeyComboBox {
            get {
                return ((string)(this["ThisVirtualKeyComboBox"]));
            }
            set {
                this["ThisVirtualKeyComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListUnableWindow {
            get {
                return ((bool)(this["ListUnableWindow"]));
            }
            set {
                this["ListUnableWindow"] = value;
            }
        }
    }
}
